"""Add AES-256 encryption columns

Revision ID: b82169a4e57a
Revises: 
Create Date: 2025-12-30 09:42:48.735879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b82169a4e57a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('poll_options', schema=None) as batch_op:
        batch_op.add_column(sa.Column('option_encrypted', sa.Text(), nullable=True))

    with op.batch_alter_table('polls', schema=None) as batch_op:
        batch_op.add_column(sa.Column('question_encrypted', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('is_encrypted', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('polls', schema=None) as batch_op:
        batch_op.drop_column('is_encrypted')
        batch_op.drop_column('question_encrypted')

    with op.batch_alter_table('poll_options', schema=None) as batch_op:
        batch_op.drop_column('option_encrypted')

    # ### end Alembic commands ###
